# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
domainInfo:
  AdminUserName: '@@SECRET:__weblogic-credentials__:username@@'
  AdminPassword: '@@SECRET:__weblogic-credentials__:password@@'
  ServerStartMode: 'prod'

topology:
  Name: 'bobbys-front-end'
  AdminServerName: 'AdminServer'
  ProductionModeEnabled: true
  Cluster:
    'cluster-1':
      DynamicServers:
        ServerTemplate: 'cluster-1-template'
        CalculatedListenPorts: false
        ServerNamePrefix: 'managed-server'
        DynamicClusterSize: '5'
        MaxDynamicClusterSize: '5'
  Server:
    'AdminServer':
      ListenPort: '7001'
      NetworkAccessPoint:
        'T3Channel':
          PublicPort: '30101'
          PublicAddress: 'bobbys-front-end-adminserver'
          ListenAddress: 127.0.0.1
          ListenPort: '30101'
  ServerTemplate:
    'cluster-1-template':
      ListenPort: '8001'
      # Disable MSI mode to prevent startup issues when admin server terminates unexpectedly
      ManagedServerIndependenceEnabled: false
      Cluster: 'cluster-1'
      ListenAddress: 'bobbys-front-end-managed-server${id}'

appDeployments:
  Application:
    # Quote needed because of hyphen in string
    'bobbys-front-end':
      SourcePath: 'wlsdeploy/apps/bobbys-front-end.war'
      Target: 'cluster-1'
      ModuleType: war
      StagingMode: nostage
      PlanStagingMode: nostage
