# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
---
kind: Service
apiVersion: v1
metadata:
  name: roberts-helidon-stock-application
  namespace: robert
  labels:
    app: roberts-helidon-stock-application
    species: helidon
spec:
  type: NodePort
  selector:
    app: roberts-helidon-stock-application
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: roberts-helidon-stock-application
  namespace: robert
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: roberts-helidon-stock-application
        version: v1
        species: helidon
    spec:
      containers:
      - name: roberts-helidon-stock-application
        image: docker.pkg.github.com/verrazzano/examples/roberts-helidon-stock-application:0.1.6-mark
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ocir
  selector:
    matchLabels:
      app: bobbys-helidon-stock-application
      version: v1
      species: helidon
---
