# Copyright (c) 2020, Oracle Corporation and/or its affiliates

domainInfo:
  AdminUserName: 'weblogic'
  AdminPassword: '@@PROP:admin.password@@'
  ServerStartMode: 'prod'
  domainLibraries: [ 'wlsdeploy/domainLibraries/mysql-connector-java-commercial-8.0.20.jar',
                     'wlsdeploy/domainLibraries/opentracing-jdbc-0.2.2.jar',
                     'wlsdeploy/domainLibraries/opentracing-noop-0.33.0.jar',
                     'wlsdeploy/domainLibraries/opentracing-util-0.33.0.jar',
                     'wlsdeploy/domainLibraries/opentracing-api-0.33.0.jar' ]

topology:
  Name: 'bobs-bookstore'
  AdminServerName: 'admin-server'
  ProductionModeEnabled: true
  Cluster:
    'cluster-1':
      DynamicServers:
        ServerTemplate: 'cluster-1-template'
        CalculatedListenPorts: false
        ServerNamePrefix: 'managed-server'
        DynamicClusterSize: '2'
        MaxDynamicClusterSize: '4'
  Server:
    'admin-server':
      ListenPort: '7001'
      NetworkAccessPoint:
        'T3Channel':
          PublicPort: '30101'
          PublicAddress: 'bobs-bookstore-admin-server'
          ListenAddress: 127.0.0.1
          ListenPort: '30101'
  ServerTemplate:
    'cluster-1-template':
      ListenPort: '8001'
      Cluster: 'cluster-1'
      ListenAddress: 'bobs-bookstore-managed-server-${id}'

resources:
  JDBCSystemResource:
    books:
      Target: 'cluster-1'
      JdbcResource:
        JDBCDataSourceParams:
          JNDIName: [
            jdbc/books
          ]
        JDBCDriverParams:
          #DriverName: io.opentracing.contrib.jdbc.TracingDriver
          #URL : 'jdbc:tracing:mysql:@//mysql:3006/books'
          DriverName: com.mysql.cj.jdbc.Driver
          URL : 'jdbc:mysql://mysql:3006/books'
          PasswordEncrypted: '@@PROP:db.password@@'
          Properties:
            user:
              Value: books

appDeployments:
  Application:
    # Quote needed because of hyphen in string
    'bobs-bookstore-order-manager':
      SourcePath: 'wlsdeploy/apps/bobs-bookstore-order-manager.war'
      Target: 'cluster-1'
      ModuleType: war
      StagingMode: nostage
      PlanStagingMode: nostage


