# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

domainInfo:
  AdminUserName: '@@SECRET:__weblogic-credentials__:username@@'
  AdminPassword: '@@SECRET:__weblogic-credentials__:password@@'
  ServerStartMode: 'prod'
  domainLibraries: [ 'wlsdeploy/domainLibraries/mysql-connector-java-commercial-8.0.20.jar',
                     'wlsdeploy/domainLibraries/opentracing-jdbc-0.2.2.jar',
                     'wlsdeploy/domainLibraries/opentracing-noop-0.33.0.jar',
                     'wlsdeploy/domainLibraries/opentracing-util-0.33.0.jar',
                     'wlsdeploy/domainLibraries/opentracing-api-0.33.0.jar' ]

topology:
  Name: 'bobs-bookstore'
  AdminServerName: 'AdminServer'
  ProductionModeEnabled: true
  Cluster:
    'cluster-1':
      DynamicServers:
        ServerTemplate: 'cluster-1-template'
        CalculatedListenPorts: false
        ServerNamePrefix: 'managed-server'
        DynamicClusterSize: '2'
        MaxDynamicClusterSize: '4'
  Server:
    'AdminServer':
      ListenPort: '7001'
      NetworkAccessPoint:
        'T3Channel':
          PublicPort: '30101'
          PublicAddress: 'bobs-bookstore-adminserver'
          ListenAddress: 127.0.0.1
          ListenPort: '30101'
  ServerTemplate:
    'cluster-1-template':
      ListenPort: '8001'
      # Disable MSI mode to prevent startup issues when admin server terminates unexpectedly
      ManagedServerIndependenceEnabled: false
      Cluster: 'cluster-1'
      ListenAddress: 'bobs-bookstore-managed-server-${id}'
      NetworkAccessPoint:
        Ch_ONLINE_BPM:
          HttpEnabledForThisProtocol: false
          ListenAddress: '@@ENV:DOMAIN_UID@@-managed-server${id}'
          ListenPort: '27401'

appDeployments:
  Application:
    # Quote needed because of hyphen in string
    'bobs-bookstore-order-manager':
      SourcePath: 'wlsdeploy/apps/bobs-bookstore-order-manager.war'
      Target: 'cluster-1'
      ModuleType: war
      StagingMode: nostage
      PlanStagingMode: nostage
