# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
---
kind: Service
apiVersion: v1
metadata:
  name: bobbys-helidon-stock-application
  namespace: bobby
  labels:
    app: bobbys-helidon-stock-application
    species: helidon
spec:
  type: NodePort
  selector:
    app: bobbys-helidon-stock-application
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bobbys-helidon-stock-application
  namespace: bobby
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bobbys-helidon-stock-application
        version: v1
        species: helidon
    spec:
      containers:
      - name: bobbys-helidon-stock-application
        image: "docker.pkg.github.com/verrazzano/examples/bobbys-helidon-stock-application:0.1.6-mark"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: BACKEND_HOSTNAME
            value: "bobs-bookstore-cluster-cluster-1.bob.svc.cluster.local"
          - name: BACKEND_PORT
            value: "31111"
      imagePullSecrets:
        - name: ocir
  selector:
    matchLabels:
      app: bobbys-helidon-stock-application
      version: v1
      species: helidon
---
